services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6380
      - API_BASE_URL=https://jsonplaceholder.typicode.com
    depends_on:
      - redis

volumes:
  redis_data: